version: '3'

services:
  web:
    build: .
    depends_on:
      - db
    volumes:
      - .:/v1
    container_name: fastapi_container2
    environment:
      - DATABASE_URL=postgresql://postgres:password@localhost:5433/todos
    ports:
      - "9000:9000"
    command: uvicorn main:app --reload --host=0.0.0.0 --port 9000

  db:
      image: postgres:15-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      expose:
        - 5433
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=todos

volumes:
      postgres_data: